# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lucas/Documents/Code/Ash

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lucas/Documents/Code/Ash

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas/Documents/Code/Ash/CMakeFiles /home/lucas/Documents/Code/Ash//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas/Documents/Code/Ash/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Ash

# Build rule for target.
Ash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Ash
.PHONY : Ash

# fast build rule for target.
Ash/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/build
.PHONY : Ash/fast

#=============================================================================
# Target rules for targets named GLFW

# Build rule for target.
GLFW: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GLFW
.PHONY : GLFW

# fast build rule for target.
GLFW/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/build
.PHONY : GLFW/fast

#=============================================================================
# Target rules for targets named ImGui

# Build rule for target.
ImGui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ImGui
.PHONY : ImGui

# fast build rule for target.
ImGui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/build
.PHONY : ImGui/fast

# target to build an object file
cmake_pch.hxx.gch:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/cmake_pch.hxx.gch
.PHONY : cmake_pch.hxx.gch

# target to preprocess a source file
cmake_pch.hxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/cmake_pch.hxx.i
.PHONY : cmake_pch.hxx.i

# target to generate assembly for a file
cmake_pch.hxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/cmake_pch.hxx.s
.PHONY : cmake_pch.hxx.s

src/Components/BasicMovementComponent.o: src/Components/BasicMovementComponent.cpp.o
.PHONY : src/Components/BasicMovementComponent.o

# target to build an object file
src/Components/BasicMovementComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/BasicMovementComponent.cpp.o
.PHONY : src/Components/BasicMovementComponent.cpp.o

src/Components/BasicMovementComponent.i: src/Components/BasicMovementComponent.cpp.i
.PHONY : src/Components/BasicMovementComponent.i

# target to preprocess a source file
src/Components/BasicMovementComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/BasicMovementComponent.cpp.i
.PHONY : src/Components/BasicMovementComponent.cpp.i

src/Components/BasicMovementComponent.s: src/Components/BasicMovementComponent.cpp.s
.PHONY : src/Components/BasicMovementComponent.s

# target to generate assembly for a file
src/Components/BasicMovementComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/BasicMovementComponent.cpp.s
.PHONY : src/Components/BasicMovementComponent.cpp.s

src/Components/CameraComponent.o: src/Components/CameraComponent.cpp.o
.PHONY : src/Components/CameraComponent.o

# target to build an object file
src/Components/CameraComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/CameraComponent.cpp.o
.PHONY : src/Components/CameraComponent.cpp.o

src/Components/CameraComponent.i: src/Components/CameraComponent.cpp.i
.PHONY : src/Components/CameraComponent.i

# target to preprocess a source file
src/Components/CameraComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/CameraComponent.cpp.i
.PHONY : src/Components/CameraComponent.cpp.i

src/Components/CameraComponent.s: src/Components/CameraComponent.cpp.s
.PHONY : src/Components/CameraComponent.s

# target to generate assembly for a file
src/Components/CameraComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/CameraComponent.cpp.s
.PHONY : src/Components/CameraComponent.cpp.s

src/Components/Component.o: src/Components/Component.cpp.o
.PHONY : src/Components/Component.o

# target to build an object file
src/Components/Component.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/Component.cpp.o
.PHONY : src/Components/Component.cpp.o

src/Components/Component.i: src/Components/Component.cpp.i
.PHONY : src/Components/Component.i

# target to preprocess a source file
src/Components/Component.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/Component.cpp.i
.PHONY : src/Components/Component.cpp.i

src/Components/Component.s: src/Components/Component.cpp.s
.PHONY : src/Components/Component.s

# target to generate assembly for a file
src/Components/Component.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/Component.cpp.s
.PHONY : src/Components/Component.cpp.s

src/Components/LightComponent.o: src/Components/LightComponent.cpp.o
.PHONY : src/Components/LightComponent.o

# target to build an object file
src/Components/LightComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/LightComponent.cpp.o
.PHONY : src/Components/LightComponent.cpp.o

src/Components/LightComponent.i: src/Components/LightComponent.cpp.i
.PHONY : src/Components/LightComponent.i

# target to preprocess a source file
src/Components/LightComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/LightComponent.cpp.i
.PHONY : src/Components/LightComponent.cpp.i

src/Components/LightComponent.s: src/Components/LightComponent.cpp.s
.PHONY : src/Components/LightComponent.s

# target to generate assembly for a file
src/Components/LightComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/LightComponent.cpp.s
.PHONY : src/Components/LightComponent.cpp.s

src/Components/ModelComponent.o: src/Components/ModelComponent.cpp.o
.PHONY : src/Components/ModelComponent.o

# target to build an object file
src/Components/ModelComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/ModelComponent.cpp.o
.PHONY : src/Components/ModelComponent.cpp.o

src/Components/ModelComponent.i: src/Components/ModelComponent.cpp.i
.PHONY : src/Components/ModelComponent.i

# target to preprocess a source file
src/Components/ModelComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/ModelComponent.cpp.i
.PHONY : src/Components/ModelComponent.cpp.i

src/Components/ModelComponent.s: src/Components/ModelComponent.cpp.s
.PHONY : src/Components/ModelComponent.s

# target to generate assembly for a file
src/Components/ModelComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/ModelComponent.cpp.s
.PHONY : src/Components/ModelComponent.cpp.s

src/Components/TagComponent.o: src/Components/TagComponent.cpp.o
.PHONY : src/Components/TagComponent.o

# target to build an object file
src/Components/TagComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/TagComponent.cpp.o
.PHONY : src/Components/TagComponent.cpp.o

src/Components/TagComponent.i: src/Components/TagComponent.cpp.i
.PHONY : src/Components/TagComponent.i

# target to preprocess a source file
src/Components/TagComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/TagComponent.cpp.i
.PHONY : src/Components/TagComponent.cpp.i

src/Components/TagComponent.s: src/Components/TagComponent.cpp.s
.PHONY : src/Components/TagComponent.s

# target to generate assembly for a file
src/Components/TagComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/TagComponent.cpp.s
.PHONY : src/Components/TagComponent.cpp.s

src/Components/TransformComponent.o: src/Components/TransformComponent.cpp.o
.PHONY : src/Components/TransformComponent.o

# target to build an object file
src/Components/TransformComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/TransformComponent.cpp.o
.PHONY : src/Components/TransformComponent.cpp.o

src/Components/TransformComponent.i: src/Components/TransformComponent.cpp.i
.PHONY : src/Components/TransformComponent.i

# target to preprocess a source file
src/Components/TransformComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/TransformComponent.cpp.i
.PHONY : src/Components/TransformComponent.cpp.i

src/Components/TransformComponent.s: src/Components/TransformComponent.cpp.s
.PHONY : src/Components/TransformComponent.s

# target to generate assembly for a file
src/Components/TransformComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Components/TransformComponent.cpp.s
.PHONY : src/Components/TransformComponent.cpp.s

src/Config/Config.o: src/Config/Config.cpp.o
.PHONY : src/Config/Config.o

# target to build an object file
src/Config/Config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Config/Config.cpp.o
.PHONY : src/Config/Config.cpp.o

src/Config/Config.i: src/Config/Config.cpp.i
.PHONY : src/Config/Config.i

# target to preprocess a source file
src/Config/Config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Config/Config.cpp.i
.PHONY : src/Config/Config.cpp.i

src/Config/Config.s: src/Config/Config.cpp.s
.PHONY : src/Config/Config.s

# target to generate assembly for a file
src/Config/Config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Config/Config.cpp.s
.PHONY : src/Config/Config.cpp.s

src/Core/ErrorCallbacks.o: src/Core/ErrorCallbacks.cpp.o
.PHONY : src/Core/ErrorCallbacks.o

# target to build an object file
src/Core/ErrorCallbacks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Core/ErrorCallbacks.cpp.o
.PHONY : src/Core/ErrorCallbacks.cpp.o

src/Core/ErrorCallbacks.i: src/Core/ErrorCallbacks.cpp.i
.PHONY : src/Core/ErrorCallbacks.i

# target to preprocess a source file
src/Core/ErrorCallbacks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Core/ErrorCallbacks.cpp.i
.PHONY : src/Core/ErrorCallbacks.cpp.i

src/Core/ErrorCallbacks.s: src/Core/ErrorCallbacks.cpp.s
.PHONY : src/Core/ErrorCallbacks.s

# target to generate assembly for a file
src/Core/ErrorCallbacks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Core/ErrorCallbacks.cpp.s
.PHONY : src/Core/ErrorCallbacks.cpp.s

src/Core/Log.o: src/Core/Log.cpp.o
.PHONY : src/Core/Log.o

# target to build an object file
src/Core/Log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Core/Log.cpp.o
.PHONY : src/Core/Log.cpp.o

src/Core/Log.i: src/Core/Log.cpp.i
.PHONY : src/Core/Log.i

# target to preprocess a source file
src/Core/Log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Core/Log.cpp.i
.PHONY : src/Core/Log.cpp.i

src/Core/Log.s: src/Core/Log.cpp.s
.PHONY : src/Core/Log.s

# target to generate assembly for a file
src/Core/Log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Core/Log.cpp.s
.PHONY : src/Core/Log.cpp.s

src/Entity/Entity.o: src/Entity/Entity.cpp.o
.PHONY : src/Entity/Entity.o

# target to build an object file
src/Entity/Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Entity/Entity.cpp.o
.PHONY : src/Entity/Entity.cpp.o

src/Entity/Entity.i: src/Entity/Entity.cpp.i
.PHONY : src/Entity/Entity.i

# target to preprocess a source file
src/Entity/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Entity/Entity.cpp.i
.PHONY : src/Entity/Entity.cpp.i

src/Entity/Entity.s: src/Entity/Entity.cpp.s
.PHONY : src/Entity/Entity.s

# target to generate assembly for a file
src/Entity/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Entity/Entity.cpp.s
.PHONY : src/Entity/Entity.cpp.s

src/Events/Event.o: src/Events/Event.cpp.o
.PHONY : src/Events/Event.o

# target to build an object file
src/Events/Event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Events/Event.cpp.o
.PHONY : src/Events/Event.cpp.o

src/Events/Event.i: src/Events/Event.cpp.i
.PHONY : src/Events/Event.i

# target to preprocess a source file
src/Events/Event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Events/Event.cpp.i
.PHONY : src/Events/Event.cpp.i

src/Events/Event.s: src/Events/Event.cpp.s
.PHONY : src/Events/Event.s

# target to generate assembly for a file
src/Events/Event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Events/Event.cpp.s
.PHONY : src/Events/Event.cpp.s

src/Events/EventDispatcher.o: src/Events/EventDispatcher.cpp.o
.PHONY : src/Events/EventDispatcher.o

# target to build an object file
src/Events/EventDispatcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Events/EventDispatcher.cpp.o
.PHONY : src/Events/EventDispatcher.cpp.o

src/Events/EventDispatcher.i: src/Events/EventDispatcher.cpp.i
.PHONY : src/Events/EventDispatcher.i

# target to preprocess a source file
src/Events/EventDispatcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Events/EventDispatcher.cpp.i
.PHONY : src/Events/EventDispatcher.cpp.i

src/Events/EventDispatcher.s: src/Events/EventDispatcher.cpp.s
.PHONY : src/Events/EventDispatcher.s

# target to generate assembly for a file
src/Events/EventDispatcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Events/EventDispatcher.cpp.s
.PHONY : src/Events/EventDispatcher.cpp.s

src/Input/Input.o: src/Input/Input.cpp.o
.PHONY : src/Input/Input.o

# target to build an object file
src/Input/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Input/Input.cpp.o
.PHONY : src/Input/Input.cpp.o

src/Input/Input.i: src/Input/Input.cpp.i
.PHONY : src/Input/Input.i

# target to preprocess a source file
src/Input/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Input/Input.cpp.i
.PHONY : src/Input/Input.cpp.i

src/Input/Input.s: src/Input/Input.cpp.s
.PHONY : src/Input/Input.s

# target to generate assembly for a file
src/Input/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Input/Input.cpp.s
.PHONY : src/Input/Input.cpp.s

src/Model/Model.o: src/Model/Model.cpp.o
.PHONY : src/Model/Model.o

# target to build an object file
src/Model/Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Model/Model.cpp.o
.PHONY : src/Model/Model.cpp.o

src/Model/Model.i: src/Model/Model.cpp.i
.PHONY : src/Model/Model.i

# target to preprocess a source file
src/Model/Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Model/Model.cpp.i
.PHONY : src/Model/Model.cpp.i

src/Model/Model.s: src/Model/Model.cpp.s
.PHONY : src/Model/Model.s

# target to generate assembly for a file
src/Model/Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Model/Model.cpp.s
.PHONY : src/Model/Model.cpp.s

src/Scene/Scene.o: src/Scene/Scene.cpp.o
.PHONY : src/Scene/Scene.o

# target to build an object file
src/Scene/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Scene/Scene.cpp.o
.PHONY : src/Scene/Scene.cpp.o

src/Scene/Scene.i: src/Scene/Scene.cpp.i
.PHONY : src/Scene/Scene.i

# target to preprocess a source file
src/Scene/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Scene/Scene.cpp.i
.PHONY : src/Scene/Scene.cpp.i

src/Scene/Scene.s: src/Scene/Scene.cpp.s
.PHONY : src/Scene/Scene.s

# target to generate assembly for a file
src/Scene/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Scene/Scene.cpp.s
.PHONY : src/Scene/Scene.cpp.s

src/Utility/File.o: src/Utility/File.cpp.o
.PHONY : src/Utility/File.o

# target to build an object file
src/Utility/File.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Utility/File.cpp.o
.PHONY : src/Utility/File.cpp.o

src/Utility/File.i: src/Utility/File.cpp.i
.PHONY : src/Utility/File.i

# target to preprocess a source file
src/Utility/File.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Utility/File.cpp.i
.PHONY : src/Utility/File.cpp.i

src/Utility/File.s: src/Utility/File.cpp.s
.PHONY : src/Utility/File.s

# target to generate assembly for a file
src/Utility/File.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Utility/File.cpp.s
.PHONY : src/Utility/File.cpp.s

src/Vulkan/Buffer/Buffer.o: src/Vulkan/Buffer/Buffer.cpp.o
.PHONY : src/Vulkan/Buffer/Buffer.o

# target to build an object file
src/Vulkan/Buffer/Buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Buffer/Buffer.cpp.o
.PHONY : src/Vulkan/Buffer/Buffer.cpp.o

src/Vulkan/Buffer/Buffer.i: src/Vulkan/Buffer/Buffer.cpp.i
.PHONY : src/Vulkan/Buffer/Buffer.i

# target to preprocess a source file
src/Vulkan/Buffer/Buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Buffer/Buffer.cpp.i
.PHONY : src/Vulkan/Buffer/Buffer.cpp.i

src/Vulkan/Buffer/Buffer.s: src/Vulkan/Buffer/Buffer.cpp.s
.PHONY : src/Vulkan/Buffer/Buffer.s

# target to generate assembly for a file
src/Vulkan/Buffer/Buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Buffer/Buffer.cpp.s
.PHONY : src/Vulkan/Buffer/Buffer.cpp.s

src/Vulkan/Context/Context.o: src/Vulkan/Context/Context.cpp.o
.PHONY : src/Vulkan/Context/Context.o

# target to build an object file
src/Vulkan/Context/Context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Context/Context.cpp.o
.PHONY : src/Vulkan/Context/Context.cpp.o

src/Vulkan/Context/Context.i: src/Vulkan/Context/Context.cpp.i
.PHONY : src/Vulkan/Context/Context.i

# target to preprocess a source file
src/Vulkan/Context/Context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Context/Context.cpp.i
.PHONY : src/Vulkan/Context/Context.cpp.i

src/Vulkan/Context/Context.s: src/Vulkan/Context/Context.cpp.s
.PHONY : src/Vulkan/Context/Context.s

# target to generate assembly for a file
src/Vulkan/Context/Context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Context/Context.cpp.s
.PHONY : src/Vulkan/Context/Context.cpp.s

src/Vulkan/Defaults/Defaults.o: src/Vulkan/Defaults/Defaults.cpp.o
.PHONY : src/Vulkan/Defaults/Defaults.o

# target to build an object file
src/Vulkan/Defaults/Defaults.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Defaults/Defaults.cpp.o
.PHONY : src/Vulkan/Defaults/Defaults.cpp.o

src/Vulkan/Defaults/Defaults.i: src/Vulkan/Defaults/Defaults.cpp.i
.PHONY : src/Vulkan/Defaults/Defaults.i

# target to preprocess a source file
src/Vulkan/Defaults/Defaults.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Defaults/Defaults.cpp.i
.PHONY : src/Vulkan/Defaults/Defaults.cpp.i

src/Vulkan/Defaults/Defaults.s: src/Vulkan/Defaults/Defaults.cpp.s
.PHONY : src/Vulkan/Defaults/Defaults.s

# target to generate assembly for a file
src/Vulkan/Defaults/Defaults.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Defaults/Defaults.cpp.s
.PHONY : src/Vulkan/Defaults/Defaults.cpp.s

src/Vulkan/Descriptor/Descriptor.o: src/Vulkan/Descriptor/Descriptor.cpp.o
.PHONY : src/Vulkan/Descriptor/Descriptor.o

# target to build an object file
src/Vulkan/Descriptor/Descriptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Descriptor/Descriptor.cpp.o
.PHONY : src/Vulkan/Descriptor/Descriptor.cpp.o

src/Vulkan/Descriptor/Descriptor.i: src/Vulkan/Descriptor/Descriptor.cpp.i
.PHONY : src/Vulkan/Descriptor/Descriptor.i

# target to preprocess a source file
src/Vulkan/Descriptor/Descriptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Descriptor/Descriptor.cpp.i
.PHONY : src/Vulkan/Descriptor/Descriptor.cpp.i

src/Vulkan/Descriptor/Descriptor.s: src/Vulkan/Descriptor/Descriptor.cpp.s
.PHONY : src/Vulkan/Descriptor/Descriptor.s

# target to generate assembly for a file
src/Vulkan/Descriptor/Descriptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Descriptor/Descriptor.cpp.s
.PHONY : src/Vulkan/Descriptor/Descriptor.cpp.s

src/Vulkan/Device/Device.o: src/Vulkan/Device/Device.cpp.o
.PHONY : src/Vulkan/Device/Device.o

# target to build an object file
src/Vulkan/Device/Device.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Device/Device.cpp.o
.PHONY : src/Vulkan/Device/Device.cpp.o

src/Vulkan/Device/Device.i: src/Vulkan/Device/Device.cpp.i
.PHONY : src/Vulkan/Device/Device.i

# target to preprocess a source file
src/Vulkan/Device/Device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Device/Device.cpp.i
.PHONY : src/Vulkan/Device/Device.cpp.i

src/Vulkan/Device/Device.s: src/Vulkan/Device/Device.cpp.s
.PHONY : src/Vulkan/Device/Device.s

# target to generate assembly for a file
src/Vulkan/Device/Device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Device/Device.cpp.s
.PHONY : src/Vulkan/Device/Device.cpp.s

src/Vulkan/Instance/Instance.o: src/Vulkan/Instance/Instance.cpp.o
.PHONY : src/Vulkan/Instance/Instance.o

# target to build an object file
src/Vulkan/Instance/Instance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Instance/Instance.cpp.o
.PHONY : src/Vulkan/Instance/Instance.cpp.o

src/Vulkan/Instance/Instance.i: src/Vulkan/Instance/Instance.cpp.i
.PHONY : src/Vulkan/Instance/Instance.i

# target to preprocess a source file
src/Vulkan/Instance/Instance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Instance/Instance.cpp.i
.PHONY : src/Vulkan/Instance/Instance.cpp.i

src/Vulkan/Instance/Instance.s: src/Vulkan/Instance/Instance.cpp.s
.PHONY : src/Vulkan/Instance/Instance.s

# target to generate assembly for a file
src/Vulkan/Instance/Instance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Instance/Instance.cpp.s
.PHONY : src/Vulkan/Instance/Instance.cpp.s

src/Vulkan/RenderSystem/Pipeline.o: src/Vulkan/RenderSystem/Pipeline.cpp.o
.PHONY : src/Vulkan/RenderSystem/Pipeline.o

# target to build an object file
src/Vulkan/RenderSystem/Pipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/RenderSystem/Pipeline.cpp.o
.PHONY : src/Vulkan/RenderSystem/Pipeline.cpp.o

src/Vulkan/RenderSystem/Pipeline.i: src/Vulkan/RenderSystem/Pipeline.cpp.i
.PHONY : src/Vulkan/RenderSystem/Pipeline.i

# target to preprocess a source file
src/Vulkan/RenderSystem/Pipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/RenderSystem/Pipeline.cpp.i
.PHONY : src/Vulkan/RenderSystem/Pipeline.cpp.i

src/Vulkan/RenderSystem/Pipeline.s: src/Vulkan/RenderSystem/Pipeline.cpp.s
.PHONY : src/Vulkan/RenderSystem/Pipeline.s

# target to generate assembly for a file
src/Vulkan/RenderSystem/Pipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/RenderSystem/Pipeline.cpp.s
.PHONY : src/Vulkan/RenderSystem/Pipeline.cpp.s

src/Vulkan/RenderSystem/PipelineConfig.o: src/Vulkan/RenderSystem/PipelineConfig.cpp.o
.PHONY : src/Vulkan/RenderSystem/PipelineConfig.o

# target to build an object file
src/Vulkan/RenderSystem/PipelineConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/RenderSystem/PipelineConfig.cpp.o
.PHONY : src/Vulkan/RenderSystem/PipelineConfig.cpp.o

src/Vulkan/RenderSystem/PipelineConfig.i: src/Vulkan/RenderSystem/PipelineConfig.cpp.i
.PHONY : src/Vulkan/RenderSystem/PipelineConfig.i

# target to preprocess a source file
src/Vulkan/RenderSystem/PipelineConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/RenderSystem/PipelineConfig.cpp.i
.PHONY : src/Vulkan/RenderSystem/PipelineConfig.cpp.i

src/Vulkan/RenderSystem/PipelineConfig.s: src/Vulkan/RenderSystem/PipelineConfig.cpp.s
.PHONY : src/Vulkan/RenderSystem/PipelineConfig.s

# target to generate assembly for a file
src/Vulkan/RenderSystem/PipelineConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/RenderSystem/PipelineConfig.cpp.s
.PHONY : src/Vulkan/RenderSystem/PipelineConfig.cpp.s

src/Vulkan/RenderSystem/RenderSystem.o: src/Vulkan/RenderSystem/RenderSystem.cpp.o
.PHONY : src/Vulkan/RenderSystem/RenderSystem.o

# target to build an object file
src/Vulkan/RenderSystem/RenderSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/RenderSystem/RenderSystem.cpp.o
.PHONY : src/Vulkan/RenderSystem/RenderSystem.cpp.o

src/Vulkan/RenderSystem/RenderSystem.i: src/Vulkan/RenderSystem/RenderSystem.cpp.i
.PHONY : src/Vulkan/RenderSystem/RenderSystem.i

# target to preprocess a source file
src/Vulkan/RenderSystem/RenderSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/RenderSystem/RenderSystem.cpp.i
.PHONY : src/Vulkan/RenderSystem/RenderSystem.cpp.i

src/Vulkan/RenderSystem/RenderSystem.s: src/Vulkan/RenderSystem/RenderSystem.cpp.s
.PHONY : src/Vulkan/RenderSystem/RenderSystem.s

# target to generate assembly for a file
src/Vulkan/RenderSystem/RenderSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/RenderSystem/RenderSystem.cpp.s
.PHONY : src/Vulkan/RenderSystem/RenderSystem.cpp.s

src/Vulkan/SwapChain/SwapChain.o: src/Vulkan/SwapChain/SwapChain.cpp.o
.PHONY : src/Vulkan/SwapChain/SwapChain.o

# target to build an object file
src/Vulkan/SwapChain/SwapChain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/SwapChain/SwapChain.cpp.o
.PHONY : src/Vulkan/SwapChain/SwapChain.cpp.o

src/Vulkan/SwapChain/SwapChain.i: src/Vulkan/SwapChain/SwapChain.cpp.i
.PHONY : src/Vulkan/SwapChain/SwapChain.i

# target to preprocess a source file
src/Vulkan/SwapChain/SwapChain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/SwapChain/SwapChain.cpp.i
.PHONY : src/Vulkan/SwapChain/SwapChain.cpp.i

src/Vulkan/SwapChain/SwapChain.s: src/Vulkan/SwapChain/SwapChain.cpp.s
.PHONY : src/Vulkan/SwapChain/SwapChain.s

# target to generate assembly for a file
src/Vulkan/SwapChain/SwapChain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/SwapChain/SwapChain.cpp.s
.PHONY : src/Vulkan/SwapChain/SwapChain.cpp.s

src/Vulkan/Texture/SwapChainTextures.o: src/Vulkan/Texture/SwapChainTextures.cpp.o
.PHONY : src/Vulkan/Texture/SwapChainTextures.o

# target to build an object file
src/Vulkan/Texture/SwapChainTextures.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Texture/SwapChainTextures.cpp.o
.PHONY : src/Vulkan/Texture/SwapChainTextures.cpp.o

src/Vulkan/Texture/SwapChainTextures.i: src/Vulkan/Texture/SwapChainTextures.cpp.i
.PHONY : src/Vulkan/Texture/SwapChainTextures.i

# target to preprocess a source file
src/Vulkan/Texture/SwapChainTextures.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Texture/SwapChainTextures.cpp.i
.PHONY : src/Vulkan/Texture/SwapChainTextures.cpp.i

src/Vulkan/Texture/SwapChainTextures.s: src/Vulkan/Texture/SwapChainTextures.cpp.s
.PHONY : src/Vulkan/Texture/SwapChainTextures.s

# target to generate assembly for a file
src/Vulkan/Texture/SwapChainTextures.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Texture/SwapChainTextures.cpp.s
.PHONY : src/Vulkan/Texture/SwapChainTextures.cpp.s

src/Vulkan/Texture/Texture.o: src/Vulkan/Texture/Texture.cpp.o
.PHONY : src/Vulkan/Texture/Texture.o

# target to build an object file
src/Vulkan/Texture/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Texture/Texture.cpp.o
.PHONY : src/Vulkan/Texture/Texture.cpp.o

src/Vulkan/Texture/Texture.i: src/Vulkan/Texture/Texture.cpp.i
.PHONY : src/Vulkan/Texture/Texture.i

# target to preprocess a source file
src/Vulkan/Texture/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Texture/Texture.cpp.i
.PHONY : src/Vulkan/Texture/Texture.cpp.i

src/Vulkan/Texture/Texture.s: src/Vulkan/Texture/Texture.cpp.s
.PHONY : src/Vulkan/Texture/Texture.s

# target to generate assembly for a file
src/Vulkan/Texture/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Texture/Texture.cpp.s
.PHONY : src/Vulkan/Texture/Texture.cpp.s

src/Vulkan/Utility/Commands/SingleTimeCommands.o: src/Vulkan/Utility/Commands/SingleTimeCommands.cpp.o
.PHONY : src/Vulkan/Utility/Commands/SingleTimeCommands.o

# target to build an object file
src/Vulkan/Utility/Commands/SingleTimeCommands.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Utility/Commands/SingleTimeCommands.cpp.o
.PHONY : src/Vulkan/Utility/Commands/SingleTimeCommands.cpp.o

src/Vulkan/Utility/Commands/SingleTimeCommands.i: src/Vulkan/Utility/Commands/SingleTimeCommands.cpp.i
.PHONY : src/Vulkan/Utility/Commands/SingleTimeCommands.i

# target to preprocess a source file
src/Vulkan/Utility/Commands/SingleTimeCommands.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Utility/Commands/SingleTimeCommands.cpp.i
.PHONY : src/Vulkan/Utility/Commands/SingleTimeCommands.cpp.i

src/Vulkan/Utility/Commands/SingleTimeCommands.s: src/Vulkan/Utility/Commands/SingleTimeCommands.cpp.s
.PHONY : src/Vulkan/Utility/Commands/SingleTimeCommands.s

# target to generate assembly for a file
src/Vulkan/Utility/Commands/SingleTimeCommands.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Utility/Commands/SingleTimeCommands.cpp.s
.PHONY : src/Vulkan/Utility/Commands/SingleTimeCommands.cpp.s

src/Vulkan/Utility/Shapes/Cube.o: src/Vulkan/Utility/Shapes/Cube.cpp.o
.PHONY : src/Vulkan/Utility/Shapes/Cube.o

# target to build an object file
src/Vulkan/Utility/Shapes/Cube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Utility/Shapes/Cube.cpp.o
.PHONY : src/Vulkan/Utility/Shapes/Cube.cpp.o

src/Vulkan/Utility/Shapes/Cube.i: src/Vulkan/Utility/Shapes/Cube.cpp.i
.PHONY : src/Vulkan/Utility/Shapes/Cube.i

# target to preprocess a source file
src/Vulkan/Utility/Shapes/Cube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Utility/Shapes/Cube.cpp.i
.PHONY : src/Vulkan/Utility/Shapes/Cube.cpp.i

src/Vulkan/Utility/Shapes/Cube.s: src/Vulkan/Utility/Shapes/Cube.cpp.s
.PHONY : src/Vulkan/Utility/Shapes/Cube.s

# target to generate assembly for a file
src/Vulkan/Utility/Shapes/Cube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Utility/Shapes/Cube.cpp.s
.PHONY : src/Vulkan/Utility/Shapes/Cube.cpp.s

src/Vulkan/Utility/Shapes/Quad.o: src/Vulkan/Utility/Shapes/Quad.cpp.o
.PHONY : src/Vulkan/Utility/Shapes/Quad.o

# target to build an object file
src/Vulkan/Utility/Shapes/Quad.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Utility/Shapes/Quad.cpp.o
.PHONY : src/Vulkan/Utility/Shapes/Quad.cpp.o

src/Vulkan/Utility/Shapes/Quad.i: src/Vulkan/Utility/Shapes/Quad.cpp.i
.PHONY : src/Vulkan/Utility/Shapes/Quad.i

# target to preprocess a source file
src/Vulkan/Utility/Shapes/Quad.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Utility/Shapes/Quad.cpp.i
.PHONY : src/Vulkan/Utility/Shapes/Quad.cpp.i

src/Vulkan/Utility/Shapes/Quad.s: src/Vulkan/Utility/Shapes/Quad.cpp.s
.PHONY : src/Vulkan/Utility/Shapes/Quad.s

# target to generate assembly for a file
src/Vulkan/Utility/Shapes/Quad.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Utility/Shapes/Quad.cpp.s
.PHONY : src/Vulkan/Utility/Shapes/Quad.cpp.s

src/Vulkan/Window/Window.o: src/Vulkan/Window/Window.cpp.o
.PHONY : src/Vulkan/Window/Window.o

# target to build an object file
src/Vulkan/Window/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Window/Window.cpp.o
.PHONY : src/Vulkan/Window/Window.cpp.o

src/Vulkan/Window/Window.i: src/Vulkan/Window/Window.cpp.i
.PHONY : src/Vulkan/Window/Window.i

# target to preprocess a source file
src/Vulkan/Window/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Window/Window.cpp.i
.PHONY : src/Vulkan/Window/Window.cpp.i

src/Vulkan/Window/Window.s: src/Vulkan/Window/Window.cpp.s
.PHONY : src/Vulkan/Window/Window.s

# target to generate assembly for a file
src/Vulkan/Window/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/Vulkan/Window/Window.cpp.s
.PHONY : src/Vulkan/Window/Window.cpp.s

src/pch.o: src/pch.cpp.o
.PHONY : src/pch.o

# target to build an object file
src/pch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/pch.cpp.o
.PHONY : src/pch.cpp.o

src/pch.i: src/pch.cpp.i
.PHONY : src/pch.i

# target to preprocess a source file
src/pch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/pch.cpp.i
.PHONY : src/pch.cpp.i

src/pch.s: src/pch.cpp.s
.PHONY : src/pch.s

# target to generate assembly for a file
src/pch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ash.dir/build.make CMakeFiles/Ash.dir/src/pch.cpp.s
.PHONY : src/pch.cpp.s

vendor/glfw/glfw/src/context.o: vendor/glfw/glfw/src/context.c.o
.PHONY : vendor/glfw/glfw/src/context.o

# target to build an object file
vendor/glfw/glfw/src/context.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/context.c.o
.PHONY : vendor/glfw/glfw/src/context.c.o

vendor/glfw/glfw/src/context.i: vendor/glfw/glfw/src/context.c.i
.PHONY : vendor/glfw/glfw/src/context.i

# target to preprocess a source file
vendor/glfw/glfw/src/context.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/context.c.i
.PHONY : vendor/glfw/glfw/src/context.c.i

vendor/glfw/glfw/src/context.s: vendor/glfw/glfw/src/context.c.s
.PHONY : vendor/glfw/glfw/src/context.s

# target to generate assembly for a file
vendor/glfw/glfw/src/context.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/context.c.s
.PHONY : vendor/glfw/glfw/src/context.c.s

vendor/glfw/glfw/src/egl_context.o: vendor/glfw/glfw/src/egl_context.c.o
.PHONY : vendor/glfw/glfw/src/egl_context.o

# target to build an object file
vendor/glfw/glfw/src/egl_context.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/egl_context.c.o
.PHONY : vendor/glfw/glfw/src/egl_context.c.o

vendor/glfw/glfw/src/egl_context.i: vendor/glfw/glfw/src/egl_context.c.i
.PHONY : vendor/glfw/glfw/src/egl_context.i

# target to preprocess a source file
vendor/glfw/glfw/src/egl_context.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/egl_context.c.i
.PHONY : vendor/glfw/glfw/src/egl_context.c.i

vendor/glfw/glfw/src/egl_context.s: vendor/glfw/glfw/src/egl_context.c.s
.PHONY : vendor/glfw/glfw/src/egl_context.s

# target to generate assembly for a file
vendor/glfw/glfw/src/egl_context.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/egl_context.c.s
.PHONY : vendor/glfw/glfw/src/egl_context.c.s

vendor/glfw/glfw/src/glx_context.o: vendor/glfw/glfw/src/glx_context.c.o
.PHONY : vendor/glfw/glfw/src/glx_context.o

# target to build an object file
vendor/glfw/glfw/src/glx_context.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/glx_context.c.o
.PHONY : vendor/glfw/glfw/src/glx_context.c.o

vendor/glfw/glfw/src/glx_context.i: vendor/glfw/glfw/src/glx_context.c.i
.PHONY : vendor/glfw/glfw/src/glx_context.i

# target to preprocess a source file
vendor/glfw/glfw/src/glx_context.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/glx_context.c.i
.PHONY : vendor/glfw/glfw/src/glx_context.c.i

vendor/glfw/glfw/src/glx_context.s: vendor/glfw/glfw/src/glx_context.c.s
.PHONY : vendor/glfw/glfw/src/glx_context.s

# target to generate assembly for a file
vendor/glfw/glfw/src/glx_context.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/glx_context.c.s
.PHONY : vendor/glfw/glfw/src/glx_context.c.s

vendor/glfw/glfw/src/init.o: vendor/glfw/glfw/src/init.c.o
.PHONY : vendor/glfw/glfw/src/init.o

# target to build an object file
vendor/glfw/glfw/src/init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/init.c.o
.PHONY : vendor/glfw/glfw/src/init.c.o

vendor/glfw/glfw/src/init.i: vendor/glfw/glfw/src/init.c.i
.PHONY : vendor/glfw/glfw/src/init.i

# target to preprocess a source file
vendor/glfw/glfw/src/init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/init.c.i
.PHONY : vendor/glfw/glfw/src/init.c.i

vendor/glfw/glfw/src/init.s: vendor/glfw/glfw/src/init.c.s
.PHONY : vendor/glfw/glfw/src/init.s

# target to generate assembly for a file
vendor/glfw/glfw/src/init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/init.c.s
.PHONY : vendor/glfw/glfw/src/init.c.s

vendor/glfw/glfw/src/input.o: vendor/glfw/glfw/src/input.c.o
.PHONY : vendor/glfw/glfw/src/input.o

# target to build an object file
vendor/glfw/glfw/src/input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/input.c.o
.PHONY : vendor/glfw/glfw/src/input.c.o

vendor/glfw/glfw/src/input.i: vendor/glfw/glfw/src/input.c.i
.PHONY : vendor/glfw/glfw/src/input.i

# target to preprocess a source file
vendor/glfw/glfw/src/input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/input.c.i
.PHONY : vendor/glfw/glfw/src/input.c.i

vendor/glfw/glfw/src/input.s: vendor/glfw/glfw/src/input.c.s
.PHONY : vendor/glfw/glfw/src/input.s

# target to generate assembly for a file
vendor/glfw/glfw/src/input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/input.c.s
.PHONY : vendor/glfw/glfw/src/input.c.s

vendor/glfw/glfw/src/linux_joystick.o: vendor/glfw/glfw/src/linux_joystick.c.o
.PHONY : vendor/glfw/glfw/src/linux_joystick.o

# target to build an object file
vendor/glfw/glfw/src/linux_joystick.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/linux_joystick.c.o
.PHONY : vendor/glfw/glfw/src/linux_joystick.c.o

vendor/glfw/glfw/src/linux_joystick.i: vendor/glfw/glfw/src/linux_joystick.c.i
.PHONY : vendor/glfw/glfw/src/linux_joystick.i

# target to preprocess a source file
vendor/glfw/glfw/src/linux_joystick.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/linux_joystick.c.i
.PHONY : vendor/glfw/glfw/src/linux_joystick.c.i

vendor/glfw/glfw/src/linux_joystick.s: vendor/glfw/glfw/src/linux_joystick.c.s
.PHONY : vendor/glfw/glfw/src/linux_joystick.s

# target to generate assembly for a file
vendor/glfw/glfw/src/linux_joystick.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/linux_joystick.c.s
.PHONY : vendor/glfw/glfw/src/linux_joystick.c.s

vendor/glfw/glfw/src/monitor.o: vendor/glfw/glfw/src/monitor.c.o
.PHONY : vendor/glfw/glfw/src/monitor.o

# target to build an object file
vendor/glfw/glfw/src/monitor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/monitor.c.o
.PHONY : vendor/glfw/glfw/src/monitor.c.o

vendor/glfw/glfw/src/monitor.i: vendor/glfw/glfw/src/monitor.c.i
.PHONY : vendor/glfw/glfw/src/monitor.i

# target to preprocess a source file
vendor/glfw/glfw/src/monitor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/monitor.c.i
.PHONY : vendor/glfw/glfw/src/monitor.c.i

vendor/glfw/glfw/src/monitor.s: vendor/glfw/glfw/src/monitor.c.s
.PHONY : vendor/glfw/glfw/src/monitor.s

# target to generate assembly for a file
vendor/glfw/glfw/src/monitor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/monitor.c.s
.PHONY : vendor/glfw/glfw/src/monitor.c.s

vendor/glfw/glfw/src/null_init.o: vendor/glfw/glfw/src/null_init.c.o
.PHONY : vendor/glfw/glfw/src/null_init.o

# target to build an object file
vendor/glfw/glfw/src/null_init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/null_init.c.o
.PHONY : vendor/glfw/glfw/src/null_init.c.o

vendor/glfw/glfw/src/null_init.i: vendor/glfw/glfw/src/null_init.c.i
.PHONY : vendor/glfw/glfw/src/null_init.i

# target to preprocess a source file
vendor/glfw/glfw/src/null_init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/null_init.c.i
.PHONY : vendor/glfw/glfw/src/null_init.c.i

vendor/glfw/glfw/src/null_init.s: vendor/glfw/glfw/src/null_init.c.s
.PHONY : vendor/glfw/glfw/src/null_init.s

# target to generate assembly for a file
vendor/glfw/glfw/src/null_init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/null_init.c.s
.PHONY : vendor/glfw/glfw/src/null_init.c.s

vendor/glfw/glfw/src/null_joystick.o: vendor/glfw/glfw/src/null_joystick.c.o
.PHONY : vendor/glfw/glfw/src/null_joystick.o

# target to build an object file
vendor/glfw/glfw/src/null_joystick.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/null_joystick.c.o
.PHONY : vendor/glfw/glfw/src/null_joystick.c.o

vendor/glfw/glfw/src/null_joystick.i: vendor/glfw/glfw/src/null_joystick.c.i
.PHONY : vendor/glfw/glfw/src/null_joystick.i

# target to preprocess a source file
vendor/glfw/glfw/src/null_joystick.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/null_joystick.c.i
.PHONY : vendor/glfw/glfw/src/null_joystick.c.i

vendor/glfw/glfw/src/null_joystick.s: vendor/glfw/glfw/src/null_joystick.c.s
.PHONY : vendor/glfw/glfw/src/null_joystick.s

# target to generate assembly for a file
vendor/glfw/glfw/src/null_joystick.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/null_joystick.c.s
.PHONY : vendor/glfw/glfw/src/null_joystick.c.s

vendor/glfw/glfw/src/null_monitor.o: vendor/glfw/glfw/src/null_monitor.c.o
.PHONY : vendor/glfw/glfw/src/null_monitor.o

# target to build an object file
vendor/glfw/glfw/src/null_monitor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/null_monitor.c.o
.PHONY : vendor/glfw/glfw/src/null_monitor.c.o

vendor/glfw/glfw/src/null_monitor.i: vendor/glfw/glfw/src/null_monitor.c.i
.PHONY : vendor/glfw/glfw/src/null_monitor.i

# target to preprocess a source file
vendor/glfw/glfw/src/null_monitor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/null_monitor.c.i
.PHONY : vendor/glfw/glfw/src/null_monitor.c.i

vendor/glfw/glfw/src/null_monitor.s: vendor/glfw/glfw/src/null_monitor.c.s
.PHONY : vendor/glfw/glfw/src/null_monitor.s

# target to generate assembly for a file
vendor/glfw/glfw/src/null_monitor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/null_monitor.c.s
.PHONY : vendor/glfw/glfw/src/null_monitor.c.s

vendor/glfw/glfw/src/null_window.o: vendor/glfw/glfw/src/null_window.c.o
.PHONY : vendor/glfw/glfw/src/null_window.o

# target to build an object file
vendor/glfw/glfw/src/null_window.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/null_window.c.o
.PHONY : vendor/glfw/glfw/src/null_window.c.o

vendor/glfw/glfw/src/null_window.i: vendor/glfw/glfw/src/null_window.c.i
.PHONY : vendor/glfw/glfw/src/null_window.i

# target to preprocess a source file
vendor/glfw/glfw/src/null_window.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/null_window.c.i
.PHONY : vendor/glfw/glfw/src/null_window.c.i

vendor/glfw/glfw/src/null_window.s: vendor/glfw/glfw/src/null_window.c.s
.PHONY : vendor/glfw/glfw/src/null_window.s

# target to generate assembly for a file
vendor/glfw/glfw/src/null_window.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/null_window.c.s
.PHONY : vendor/glfw/glfw/src/null_window.c.s

vendor/glfw/glfw/src/osmesa_context.o: vendor/glfw/glfw/src/osmesa_context.c.o
.PHONY : vendor/glfw/glfw/src/osmesa_context.o

# target to build an object file
vendor/glfw/glfw/src/osmesa_context.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/osmesa_context.c.o
.PHONY : vendor/glfw/glfw/src/osmesa_context.c.o

vendor/glfw/glfw/src/osmesa_context.i: vendor/glfw/glfw/src/osmesa_context.c.i
.PHONY : vendor/glfw/glfw/src/osmesa_context.i

# target to preprocess a source file
vendor/glfw/glfw/src/osmesa_context.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/osmesa_context.c.i
.PHONY : vendor/glfw/glfw/src/osmesa_context.c.i

vendor/glfw/glfw/src/osmesa_context.s: vendor/glfw/glfw/src/osmesa_context.c.s
.PHONY : vendor/glfw/glfw/src/osmesa_context.s

# target to generate assembly for a file
vendor/glfw/glfw/src/osmesa_context.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/osmesa_context.c.s
.PHONY : vendor/glfw/glfw/src/osmesa_context.c.s

vendor/glfw/glfw/src/platform.o: vendor/glfw/glfw/src/platform.c.o
.PHONY : vendor/glfw/glfw/src/platform.o

# target to build an object file
vendor/glfw/glfw/src/platform.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/platform.c.o
.PHONY : vendor/glfw/glfw/src/platform.c.o

vendor/glfw/glfw/src/platform.i: vendor/glfw/glfw/src/platform.c.i
.PHONY : vendor/glfw/glfw/src/platform.i

# target to preprocess a source file
vendor/glfw/glfw/src/platform.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/platform.c.i
.PHONY : vendor/glfw/glfw/src/platform.c.i

vendor/glfw/glfw/src/platform.s: vendor/glfw/glfw/src/platform.c.s
.PHONY : vendor/glfw/glfw/src/platform.s

# target to generate assembly for a file
vendor/glfw/glfw/src/platform.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/platform.c.s
.PHONY : vendor/glfw/glfw/src/platform.c.s

vendor/glfw/glfw/src/posix_module.o: vendor/glfw/glfw/src/posix_module.c.o
.PHONY : vendor/glfw/glfw/src/posix_module.o

# target to build an object file
vendor/glfw/glfw/src/posix_module.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/posix_module.c.o
.PHONY : vendor/glfw/glfw/src/posix_module.c.o

vendor/glfw/glfw/src/posix_module.i: vendor/glfw/glfw/src/posix_module.c.i
.PHONY : vendor/glfw/glfw/src/posix_module.i

# target to preprocess a source file
vendor/glfw/glfw/src/posix_module.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/posix_module.c.i
.PHONY : vendor/glfw/glfw/src/posix_module.c.i

vendor/glfw/glfw/src/posix_module.s: vendor/glfw/glfw/src/posix_module.c.s
.PHONY : vendor/glfw/glfw/src/posix_module.s

# target to generate assembly for a file
vendor/glfw/glfw/src/posix_module.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/posix_module.c.s
.PHONY : vendor/glfw/glfw/src/posix_module.c.s

vendor/glfw/glfw/src/posix_poll.o: vendor/glfw/glfw/src/posix_poll.c.o
.PHONY : vendor/glfw/glfw/src/posix_poll.o

# target to build an object file
vendor/glfw/glfw/src/posix_poll.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/posix_poll.c.o
.PHONY : vendor/glfw/glfw/src/posix_poll.c.o

vendor/glfw/glfw/src/posix_poll.i: vendor/glfw/glfw/src/posix_poll.c.i
.PHONY : vendor/glfw/glfw/src/posix_poll.i

# target to preprocess a source file
vendor/glfw/glfw/src/posix_poll.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/posix_poll.c.i
.PHONY : vendor/glfw/glfw/src/posix_poll.c.i

vendor/glfw/glfw/src/posix_poll.s: vendor/glfw/glfw/src/posix_poll.c.s
.PHONY : vendor/glfw/glfw/src/posix_poll.s

# target to generate assembly for a file
vendor/glfw/glfw/src/posix_poll.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/posix_poll.c.s
.PHONY : vendor/glfw/glfw/src/posix_poll.c.s

vendor/glfw/glfw/src/posix_thread.o: vendor/glfw/glfw/src/posix_thread.c.o
.PHONY : vendor/glfw/glfw/src/posix_thread.o

# target to build an object file
vendor/glfw/glfw/src/posix_thread.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/posix_thread.c.o
.PHONY : vendor/glfw/glfw/src/posix_thread.c.o

vendor/glfw/glfw/src/posix_thread.i: vendor/glfw/glfw/src/posix_thread.c.i
.PHONY : vendor/glfw/glfw/src/posix_thread.i

# target to preprocess a source file
vendor/glfw/glfw/src/posix_thread.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/posix_thread.c.i
.PHONY : vendor/glfw/glfw/src/posix_thread.c.i

vendor/glfw/glfw/src/posix_thread.s: vendor/glfw/glfw/src/posix_thread.c.s
.PHONY : vendor/glfw/glfw/src/posix_thread.s

# target to generate assembly for a file
vendor/glfw/glfw/src/posix_thread.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/posix_thread.c.s
.PHONY : vendor/glfw/glfw/src/posix_thread.c.s

vendor/glfw/glfw/src/posix_time.o: vendor/glfw/glfw/src/posix_time.c.o
.PHONY : vendor/glfw/glfw/src/posix_time.o

# target to build an object file
vendor/glfw/glfw/src/posix_time.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/posix_time.c.o
.PHONY : vendor/glfw/glfw/src/posix_time.c.o

vendor/glfw/glfw/src/posix_time.i: vendor/glfw/glfw/src/posix_time.c.i
.PHONY : vendor/glfw/glfw/src/posix_time.i

# target to preprocess a source file
vendor/glfw/glfw/src/posix_time.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/posix_time.c.i
.PHONY : vendor/glfw/glfw/src/posix_time.c.i

vendor/glfw/glfw/src/posix_time.s: vendor/glfw/glfw/src/posix_time.c.s
.PHONY : vendor/glfw/glfw/src/posix_time.s

# target to generate assembly for a file
vendor/glfw/glfw/src/posix_time.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/posix_time.c.s
.PHONY : vendor/glfw/glfw/src/posix_time.c.s

vendor/glfw/glfw/src/vulkan.o: vendor/glfw/glfw/src/vulkan.c.o
.PHONY : vendor/glfw/glfw/src/vulkan.o

# target to build an object file
vendor/glfw/glfw/src/vulkan.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/vulkan.c.o
.PHONY : vendor/glfw/glfw/src/vulkan.c.o

vendor/glfw/glfw/src/vulkan.i: vendor/glfw/glfw/src/vulkan.c.i
.PHONY : vendor/glfw/glfw/src/vulkan.i

# target to preprocess a source file
vendor/glfw/glfw/src/vulkan.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/vulkan.c.i
.PHONY : vendor/glfw/glfw/src/vulkan.c.i

vendor/glfw/glfw/src/vulkan.s: vendor/glfw/glfw/src/vulkan.c.s
.PHONY : vendor/glfw/glfw/src/vulkan.s

# target to generate assembly for a file
vendor/glfw/glfw/src/vulkan.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/vulkan.c.s
.PHONY : vendor/glfw/glfw/src/vulkan.c.s

vendor/glfw/glfw/src/window.o: vendor/glfw/glfw/src/window.c.o
.PHONY : vendor/glfw/glfw/src/window.o

# target to build an object file
vendor/glfw/glfw/src/window.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/window.c.o
.PHONY : vendor/glfw/glfw/src/window.c.o

vendor/glfw/glfw/src/window.i: vendor/glfw/glfw/src/window.c.i
.PHONY : vendor/glfw/glfw/src/window.i

# target to preprocess a source file
vendor/glfw/glfw/src/window.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/window.c.i
.PHONY : vendor/glfw/glfw/src/window.c.i

vendor/glfw/glfw/src/window.s: vendor/glfw/glfw/src/window.c.s
.PHONY : vendor/glfw/glfw/src/window.s

# target to generate assembly for a file
vendor/glfw/glfw/src/window.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/window.c.s
.PHONY : vendor/glfw/glfw/src/window.c.s

vendor/glfw/glfw/src/x11_init.o: vendor/glfw/glfw/src/x11_init.c.o
.PHONY : vendor/glfw/glfw/src/x11_init.o

# target to build an object file
vendor/glfw/glfw/src/x11_init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/x11_init.c.o
.PHONY : vendor/glfw/glfw/src/x11_init.c.o

vendor/glfw/glfw/src/x11_init.i: vendor/glfw/glfw/src/x11_init.c.i
.PHONY : vendor/glfw/glfw/src/x11_init.i

# target to preprocess a source file
vendor/glfw/glfw/src/x11_init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/x11_init.c.i
.PHONY : vendor/glfw/glfw/src/x11_init.c.i

vendor/glfw/glfw/src/x11_init.s: vendor/glfw/glfw/src/x11_init.c.s
.PHONY : vendor/glfw/glfw/src/x11_init.s

# target to generate assembly for a file
vendor/glfw/glfw/src/x11_init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/x11_init.c.s
.PHONY : vendor/glfw/glfw/src/x11_init.c.s

vendor/glfw/glfw/src/x11_monitor.o: vendor/glfw/glfw/src/x11_monitor.c.o
.PHONY : vendor/glfw/glfw/src/x11_monitor.o

# target to build an object file
vendor/glfw/glfw/src/x11_monitor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/x11_monitor.c.o
.PHONY : vendor/glfw/glfw/src/x11_monitor.c.o

vendor/glfw/glfw/src/x11_monitor.i: vendor/glfw/glfw/src/x11_monitor.c.i
.PHONY : vendor/glfw/glfw/src/x11_monitor.i

# target to preprocess a source file
vendor/glfw/glfw/src/x11_monitor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/x11_monitor.c.i
.PHONY : vendor/glfw/glfw/src/x11_monitor.c.i

vendor/glfw/glfw/src/x11_monitor.s: vendor/glfw/glfw/src/x11_monitor.c.s
.PHONY : vendor/glfw/glfw/src/x11_monitor.s

# target to generate assembly for a file
vendor/glfw/glfw/src/x11_monitor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/x11_monitor.c.s
.PHONY : vendor/glfw/glfw/src/x11_monitor.c.s

vendor/glfw/glfw/src/x11_window.o: vendor/glfw/glfw/src/x11_window.c.o
.PHONY : vendor/glfw/glfw/src/x11_window.o

# target to build an object file
vendor/glfw/glfw/src/x11_window.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/x11_window.c.o
.PHONY : vendor/glfw/glfw/src/x11_window.c.o

vendor/glfw/glfw/src/x11_window.i: vendor/glfw/glfw/src/x11_window.c.i
.PHONY : vendor/glfw/glfw/src/x11_window.i

# target to preprocess a source file
vendor/glfw/glfw/src/x11_window.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/x11_window.c.i
.PHONY : vendor/glfw/glfw/src/x11_window.c.i

vendor/glfw/glfw/src/x11_window.s: vendor/glfw/glfw/src/x11_window.c.s
.PHONY : vendor/glfw/glfw/src/x11_window.s

# target to generate assembly for a file
vendor/glfw/glfw/src/x11_window.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/x11_window.c.s
.PHONY : vendor/glfw/glfw/src/x11_window.c.s

vendor/glfw/glfw/src/xkb_unicode.o: vendor/glfw/glfw/src/xkb_unicode.c.o
.PHONY : vendor/glfw/glfw/src/xkb_unicode.o

# target to build an object file
vendor/glfw/glfw/src/xkb_unicode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/xkb_unicode.c.o
.PHONY : vendor/glfw/glfw/src/xkb_unicode.c.o

vendor/glfw/glfw/src/xkb_unicode.i: vendor/glfw/glfw/src/xkb_unicode.c.i
.PHONY : vendor/glfw/glfw/src/xkb_unicode.i

# target to preprocess a source file
vendor/glfw/glfw/src/xkb_unicode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/xkb_unicode.c.i
.PHONY : vendor/glfw/glfw/src/xkb_unicode.c.i

vendor/glfw/glfw/src/xkb_unicode.s: vendor/glfw/glfw/src/xkb_unicode.c.s
.PHONY : vendor/glfw/glfw/src/xkb_unicode.s

# target to generate assembly for a file
vendor/glfw/glfw/src/xkb_unicode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLFW.dir/build.make CMakeFiles/GLFW.dir/vendor/glfw/glfw/src/xkb_unicode.c.s
.PHONY : vendor/glfw/glfw/src/xkb_unicode.c.s

vendor/imgui/imgui/backends/imgui_impl_glfw.o: vendor/imgui/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : vendor/imgui/imgui/backends/imgui_impl_glfw.o

# target to build an object file
vendor/imgui/imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : vendor/imgui/imgui/backends/imgui_impl_glfw.cpp.o

vendor/imgui/imgui/backends/imgui_impl_glfw.i: vendor/imgui/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : vendor/imgui/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
vendor/imgui/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : vendor/imgui/imgui/backends/imgui_impl_glfw.cpp.i

vendor/imgui/imgui/backends/imgui_impl_glfw.s: vendor/imgui/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : vendor/imgui/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
vendor/imgui/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : vendor/imgui/imgui/backends/imgui_impl_glfw.cpp.s

vendor/imgui/imgui/backends/imgui_impl_vulkan.o: vendor/imgui/imgui/backends/imgui_impl_vulkan.cpp.o
.PHONY : vendor/imgui/imgui/backends/imgui_impl_vulkan.o

# target to build an object file
vendor/imgui/imgui/backends/imgui_impl_vulkan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/backends/imgui_impl_vulkan.cpp.o
.PHONY : vendor/imgui/imgui/backends/imgui_impl_vulkan.cpp.o

vendor/imgui/imgui/backends/imgui_impl_vulkan.i: vendor/imgui/imgui/backends/imgui_impl_vulkan.cpp.i
.PHONY : vendor/imgui/imgui/backends/imgui_impl_vulkan.i

# target to preprocess a source file
vendor/imgui/imgui/backends/imgui_impl_vulkan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/backends/imgui_impl_vulkan.cpp.i
.PHONY : vendor/imgui/imgui/backends/imgui_impl_vulkan.cpp.i

vendor/imgui/imgui/backends/imgui_impl_vulkan.s: vendor/imgui/imgui/backends/imgui_impl_vulkan.cpp.s
.PHONY : vendor/imgui/imgui/backends/imgui_impl_vulkan.s

# target to generate assembly for a file
vendor/imgui/imgui/backends/imgui_impl_vulkan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/backends/imgui_impl_vulkan.cpp.s
.PHONY : vendor/imgui/imgui/backends/imgui_impl_vulkan.cpp.s

vendor/imgui/imgui/imgui.o: vendor/imgui/imgui/imgui.cpp.o
.PHONY : vendor/imgui/imgui/imgui.o

# target to build an object file
vendor/imgui/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/imgui.cpp.o
.PHONY : vendor/imgui/imgui/imgui.cpp.o

vendor/imgui/imgui/imgui.i: vendor/imgui/imgui/imgui.cpp.i
.PHONY : vendor/imgui/imgui/imgui.i

# target to preprocess a source file
vendor/imgui/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/imgui.cpp.i
.PHONY : vendor/imgui/imgui/imgui.cpp.i

vendor/imgui/imgui/imgui.s: vendor/imgui/imgui/imgui.cpp.s
.PHONY : vendor/imgui/imgui/imgui.s

# target to generate assembly for a file
vendor/imgui/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/imgui.cpp.s
.PHONY : vendor/imgui/imgui/imgui.cpp.s

vendor/imgui/imgui/imgui_demo.o: vendor/imgui/imgui/imgui_demo.cpp.o
.PHONY : vendor/imgui/imgui/imgui_demo.o

# target to build an object file
vendor/imgui/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/imgui_demo.cpp.o
.PHONY : vendor/imgui/imgui/imgui_demo.cpp.o

vendor/imgui/imgui/imgui_demo.i: vendor/imgui/imgui/imgui_demo.cpp.i
.PHONY : vendor/imgui/imgui/imgui_demo.i

# target to preprocess a source file
vendor/imgui/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/imgui_demo.cpp.i
.PHONY : vendor/imgui/imgui/imgui_demo.cpp.i

vendor/imgui/imgui/imgui_demo.s: vendor/imgui/imgui/imgui_demo.cpp.s
.PHONY : vendor/imgui/imgui/imgui_demo.s

# target to generate assembly for a file
vendor/imgui/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/imgui_demo.cpp.s
.PHONY : vendor/imgui/imgui/imgui_demo.cpp.s

vendor/imgui/imgui/imgui_draw.o: vendor/imgui/imgui/imgui_draw.cpp.o
.PHONY : vendor/imgui/imgui/imgui_draw.o

# target to build an object file
vendor/imgui/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/imgui_draw.cpp.o
.PHONY : vendor/imgui/imgui/imgui_draw.cpp.o

vendor/imgui/imgui/imgui_draw.i: vendor/imgui/imgui/imgui_draw.cpp.i
.PHONY : vendor/imgui/imgui/imgui_draw.i

# target to preprocess a source file
vendor/imgui/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/imgui_draw.cpp.i
.PHONY : vendor/imgui/imgui/imgui_draw.cpp.i

vendor/imgui/imgui/imgui_draw.s: vendor/imgui/imgui/imgui_draw.cpp.s
.PHONY : vendor/imgui/imgui/imgui_draw.s

# target to generate assembly for a file
vendor/imgui/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/imgui_draw.cpp.s
.PHONY : vendor/imgui/imgui/imgui_draw.cpp.s

vendor/imgui/imgui/imgui_tables.o: vendor/imgui/imgui/imgui_tables.cpp.o
.PHONY : vendor/imgui/imgui/imgui_tables.o

# target to build an object file
vendor/imgui/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/imgui_tables.cpp.o
.PHONY : vendor/imgui/imgui/imgui_tables.cpp.o

vendor/imgui/imgui/imgui_tables.i: vendor/imgui/imgui/imgui_tables.cpp.i
.PHONY : vendor/imgui/imgui/imgui_tables.i

# target to preprocess a source file
vendor/imgui/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/imgui_tables.cpp.i
.PHONY : vendor/imgui/imgui/imgui_tables.cpp.i

vendor/imgui/imgui/imgui_tables.s: vendor/imgui/imgui/imgui_tables.cpp.s
.PHONY : vendor/imgui/imgui/imgui_tables.s

# target to generate assembly for a file
vendor/imgui/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/imgui_tables.cpp.s
.PHONY : vendor/imgui/imgui/imgui_tables.cpp.s

vendor/imgui/imgui/imgui_widgets.o: vendor/imgui/imgui/imgui_widgets.cpp.o
.PHONY : vendor/imgui/imgui/imgui_widgets.o

# target to build an object file
vendor/imgui/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/imgui_widgets.cpp.o
.PHONY : vendor/imgui/imgui/imgui_widgets.cpp.o

vendor/imgui/imgui/imgui_widgets.i: vendor/imgui/imgui/imgui_widgets.cpp.i
.PHONY : vendor/imgui/imgui/imgui_widgets.i

# target to preprocess a source file
vendor/imgui/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/imgui_widgets.cpp.i
.PHONY : vendor/imgui/imgui/imgui_widgets.cpp.i

vendor/imgui/imgui/imgui_widgets.s: vendor/imgui/imgui/imgui_widgets.cpp.s
.PHONY : vendor/imgui/imgui/imgui_widgets.s

# target to generate assembly for a file
vendor/imgui/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImGui.dir/build.make CMakeFiles/ImGui.dir/vendor/imgui/imgui/imgui_widgets.cpp.s
.PHONY : vendor/imgui/imgui/imgui_widgets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Ash"
	@echo "... GLFW"
	@echo "... ImGui"
	@echo "... cmake_pch.hxx.gch"
	@echo "... cmake_pch.hxx.i"
	@echo "... cmake_pch.hxx.s"
	@echo "... src/Components/BasicMovementComponent.o"
	@echo "... src/Components/BasicMovementComponent.i"
	@echo "... src/Components/BasicMovementComponent.s"
	@echo "... src/Components/CameraComponent.o"
	@echo "... src/Components/CameraComponent.i"
	@echo "... src/Components/CameraComponent.s"
	@echo "... src/Components/Component.o"
	@echo "... src/Components/Component.i"
	@echo "... src/Components/Component.s"
	@echo "... src/Components/LightComponent.o"
	@echo "... src/Components/LightComponent.i"
	@echo "... src/Components/LightComponent.s"
	@echo "... src/Components/ModelComponent.o"
	@echo "... src/Components/ModelComponent.i"
	@echo "... src/Components/ModelComponent.s"
	@echo "... src/Components/TagComponent.o"
	@echo "... src/Components/TagComponent.i"
	@echo "... src/Components/TagComponent.s"
	@echo "... src/Components/TransformComponent.o"
	@echo "... src/Components/TransformComponent.i"
	@echo "... src/Components/TransformComponent.s"
	@echo "... src/Config/Config.o"
	@echo "... src/Config/Config.i"
	@echo "... src/Config/Config.s"
	@echo "... src/Core/ErrorCallbacks.o"
	@echo "... src/Core/ErrorCallbacks.i"
	@echo "... src/Core/ErrorCallbacks.s"
	@echo "... src/Core/Log.o"
	@echo "... src/Core/Log.i"
	@echo "... src/Core/Log.s"
	@echo "... src/Entity/Entity.o"
	@echo "... src/Entity/Entity.i"
	@echo "... src/Entity/Entity.s"
	@echo "... src/Events/Event.o"
	@echo "... src/Events/Event.i"
	@echo "... src/Events/Event.s"
	@echo "... src/Events/EventDispatcher.o"
	@echo "... src/Events/EventDispatcher.i"
	@echo "... src/Events/EventDispatcher.s"
	@echo "... src/Input/Input.o"
	@echo "... src/Input/Input.i"
	@echo "... src/Input/Input.s"
	@echo "... src/Model/Model.o"
	@echo "... src/Model/Model.i"
	@echo "... src/Model/Model.s"
	@echo "... src/Scene/Scene.o"
	@echo "... src/Scene/Scene.i"
	@echo "... src/Scene/Scene.s"
	@echo "... src/Utility/File.o"
	@echo "... src/Utility/File.i"
	@echo "... src/Utility/File.s"
	@echo "... src/Vulkan/Buffer/Buffer.o"
	@echo "... src/Vulkan/Buffer/Buffer.i"
	@echo "... src/Vulkan/Buffer/Buffer.s"
	@echo "... src/Vulkan/Context/Context.o"
	@echo "... src/Vulkan/Context/Context.i"
	@echo "... src/Vulkan/Context/Context.s"
	@echo "... src/Vulkan/Defaults/Defaults.o"
	@echo "... src/Vulkan/Defaults/Defaults.i"
	@echo "... src/Vulkan/Defaults/Defaults.s"
	@echo "... src/Vulkan/Descriptor/Descriptor.o"
	@echo "... src/Vulkan/Descriptor/Descriptor.i"
	@echo "... src/Vulkan/Descriptor/Descriptor.s"
	@echo "... src/Vulkan/Device/Device.o"
	@echo "... src/Vulkan/Device/Device.i"
	@echo "... src/Vulkan/Device/Device.s"
	@echo "... src/Vulkan/Instance/Instance.o"
	@echo "... src/Vulkan/Instance/Instance.i"
	@echo "... src/Vulkan/Instance/Instance.s"
	@echo "... src/Vulkan/RenderSystem/Pipeline.o"
	@echo "... src/Vulkan/RenderSystem/Pipeline.i"
	@echo "... src/Vulkan/RenderSystem/Pipeline.s"
	@echo "... src/Vulkan/RenderSystem/PipelineConfig.o"
	@echo "... src/Vulkan/RenderSystem/PipelineConfig.i"
	@echo "... src/Vulkan/RenderSystem/PipelineConfig.s"
	@echo "... src/Vulkan/RenderSystem/RenderSystem.o"
	@echo "... src/Vulkan/RenderSystem/RenderSystem.i"
	@echo "... src/Vulkan/RenderSystem/RenderSystem.s"
	@echo "... src/Vulkan/SwapChain/SwapChain.o"
	@echo "... src/Vulkan/SwapChain/SwapChain.i"
	@echo "... src/Vulkan/SwapChain/SwapChain.s"
	@echo "... src/Vulkan/Texture/SwapChainTextures.o"
	@echo "... src/Vulkan/Texture/SwapChainTextures.i"
	@echo "... src/Vulkan/Texture/SwapChainTextures.s"
	@echo "... src/Vulkan/Texture/Texture.o"
	@echo "... src/Vulkan/Texture/Texture.i"
	@echo "... src/Vulkan/Texture/Texture.s"
	@echo "... src/Vulkan/Utility/Commands/SingleTimeCommands.o"
	@echo "... src/Vulkan/Utility/Commands/SingleTimeCommands.i"
	@echo "... src/Vulkan/Utility/Commands/SingleTimeCommands.s"
	@echo "... src/Vulkan/Utility/Shapes/Cube.o"
	@echo "... src/Vulkan/Utility/Shapes/Cube.i"
	@echo "... src/Vulkan/Utility/Shapes/Cube.s"
	@echo "... src/Vulkan/Utility/Shapes/Quad.o"
	@echo "... src/Vulkan/Utility/Shapes/Quad.i"
	@echo "... src/Vulkan/Utility/Shapes/Quad.s"
	@echo "... src/Vulkan/Window/Window.o"
	@echo "... src/Vulkan/Window/Window.i"
	@echo "... src/Vulkan/Window/Window.s"
	@echo "... src/pch.o"
	@echo "... src/pch.i"
	@echo "... src/pch.s"
	@echo "... vendor/glfw/glfw/src/context.o"
	@echo "... vendor/glfw/glfw/src/context.i"
	@echo "... vendor/glfw/glfw/src/context.s"
	@echo "... vendor/glfw/glfw/src/egl_context.o"
	@echo "... vendor/glfw/glfw/src/egl_context.i"
	@echo "... vendor/glfw/glfw/src/egl_context.s"
	@echo "... vendor/glfw/glfw/src/glx_context.o"
	@echo "... vendor/glfw/glfw/src/glx_context.i"
	@echo "... vendor/glfw/glfw/src/glx_context.s"
	@echo "... vendor/glfw/glfw/src/init.o"
	@echo "... vendor/glfw/glfw/src/init.i"
	@echo "... vendor/glfw/glfw/src/init.s"
	@echo "... vendor/glfw/glfw/src/input.o"
	@echo "... vendor/glfw/glfw/src/input.i"
	@echo "... vendor/glfw/glfw/src/input.s"
	@echo "... vendor/glfw/glfw/src/linux_joystick.o"
	@echo "... vendor/glfw/glfw/src/linux_joystick.i"
	@echo "... vendor/glfw/glfw/src/linux_joystick.s"
	@echo "... vendor/glfw/glfw/src/monitor.o"
	@echo "... vendor/glfw/glfw/src/monitor.i"
	@echo "... vendor/glfw/glfw/src/monitor.s"
	@echo "... vendor/glfw/glfw/src/null_init.o"
	@echo "... vendor/glfw/glfw/src/null_init.i"
	@echo "... vendor/glfw/glfw/src/null_init.s"
	@echo "... vendor/glfw/glfw/src/null_joystick.o"
	@echo "... vendor/glfw/glfw/src/null_joystick.i"
	@echo "... vendor/glfw/glfw/src/null_joystick.s"
	@echo "... vendor/glfw/glfw/src/null_monitor.o"
	@echo "... vendor/glfw/glfw/src/null_monitor.i"
	@echo "... vendor/glfw/glfw/src/null_monitor.s"
	@echo "... vendor/glfw/glfw/src/null_window.o"
	@echo "... vendor/glfw/glfw/src/null_window.i"
	@echo "... vendor/glfw/glfw/src/null_window.s"
	@echo "... vendor/glfw/glfw/src/osmesa_context.o"
	@echo "... vendor/glfw/glfw/src/osmesa_context.i"
	@echo "... vendor/glfw/glfw/src/osmesa_context.s"
	@echo "... vendor/glfw/glfw/src/platform.o"
	@echo "... vendor/glfw/glfw/src/platform.i"
	@echo "... vendor/glfw/glfw/src/platform.s"
	@echo "... vendor/glfw/glfw/src/posix_module.o"
	@echo "... vendor/glfw/glfw/src/posix_module.i"
	@echo "... vendor/glfw/glfw/src/posix_module.s"
	@echo "... vendor/glfw/glfw/src/posix_poll.o"
	@echo "... vendor/glfw/glfw/src/posix_poll.i"
	@echo "... vendor/glfw/glfw/src/posix_poll.s"
	@echo "... vendor/glfw/glfw/src/posix_thread.o"
	@echo "... vendor/glfw/glfw/src/posix_thread.i"
	@echo "... vendor/glfw/glfw/src/posix_thread.s"
	@echo "... vendor/glfw/glfw/src/posix_time.o"
	@echo "... vendor/glfw/glfw/src/posix_time.i"
	@echo "... vendor/glfw/glfw/src/posix_time.s"
	@echo "... vendor/glfw/glfw/src/vulkan.o"
	@echo "... vendor/glfw/glfw/src/vulkan.i"
	@echo "... vendor/glfw/glfw/src/vulkan.s"
	@echo "... vendor/glfw/glfw/src/window.o"
	@echo "... vendor/glfw/glfw/src/window.i"
	@echo "... vendor/glfw/glfw/src/window.s"
	@echo "... vendor/glfw/glfw/src/x11_init.o"
	@echo "... vendor/glfw/glfw/src/x11_init.i"
	@echo "... vendor/glfw/glfw/src/x11_init.s"
	@echo "... vendor/glfw/glfw/src/x11_monitor.o"
	@echo "... vendor/glfw/glfw/src/x11_monitor.i"
	@echo "... vendor/glfw/glfw/src/x11_monitor.s"
	@echo "... vendor/glfw/glfw/src/x11_window.o"
	@echo "... vendor/glfw/glfw/src/x11_window.i"
	@echo "... vendor/glfw/glfw/src/x11_window.s"
	@echo "... vendor/glfw/glfw/src/xkb_unicode.o"
	@echo "... vendor/glfw/glfw/src/xkb_unicode.i"
	@echo "... vendor/glfw/glfw/src/xkb_unicode.s"
	@echo "... vendor/imgui/imgui/backends/imgui_impl_glfw.o"
	@echo "... vendor/imgui/imgui/backends/imgui_impl_glfw.i"
	@echo "... vendor/imgui/imgui/backends/imgui_impl_glfw.s"
	@echo "... vendor/imgui/imgui/backends/imgui_impl_vulkan.o"
	@echo "... vendor/imgui/imgui/backends/imgui_impl_vulkan.i"
	@echo "... vendor/imgui/imgui/backends/imgui_impl_vulkan.s"
	@echo "... vendor/imgui/imgui/imgui.o"
	@echo "... vendor/imgui/imgui/imgui.i"
	@echo "... vendor/imgui/imgui/imgui.s"
	@echo "... vendor/imgui/imgui/imgui_demo.o"
	@echo "... vendor/imgui/imgui/imgui_demo.i"
	@echo "... vendor/imgui/imgui/imgui_demo.s"
	@echo "... vendor/imgui/imgui/imgui_draw.o"
	@echo "... vendor/imgui/imgui/imgui_draw.i"
	@echo "... vendor/imgui/imgui/imgui_draw.s"
	@echo "... vendor/imgui/imgui/imgui_tables.o"
	@echo "... vendor/imgui/imgui/imgui_tables.i"
	@echo "... vendor/imgui/imgui/imgui_tables.s"
	@echo "... vendor/imgui/imgui/imgui_widgets.o"
	@echo "... vendor/imgui/imgui/imgui_widgets.i"
	@echo "... vendor/imgui/imgui/imgui_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

