# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  ImGui_config = debug
  Ash_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  ImGui_config = release
  Ash_config = release

else ifeq ($(config),dist)
  GLFW_config = dist
  ImGui_config = dist
  Ash_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW ImGui Ash

.PHONY: all clean help $(PROJECTS) External\ Libs

all: $(PROJECTS)

External\ Libs: GLFW ImGui

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C vendor/glfw -f Makefile config=$(GLFW_config)
endif

ImGui: GLFW
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C vendor/imgui -f Makefile config=$(ImGui_config)
endif

Ash: GLFW ImGui
ifneq (,$(Ash_config))
	@echo "==== Building Ash ($(Ash_config)) ===="
	@${MAKE} --no-print-directory -C Ash -f Makefile config=$(Ash_config)
endif

clean:
	@${MAKE} --no-print-directory -C vendor/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Ash -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   ImGui"
	@echo "   Ash"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"